[features]
seeds = false
skip-lint = false
[programs.localnet]
subscription_program = "6qMvvisbUX3Co1sZa7DkyCXF8FcsTjzKSQHcaDoqSLbw"

[registry]
url = "https://anchor.projectserum.com"

[programs.devnet]
subscription_program = "6qMvvisbUX3Co1sZa7DkyCXF8FcsTjzKSQHcaDoqSLbw"


[programs.mainnet]
subscription_program = "6qMvvisbUX3Co1sZa7DkyCXF8FcsTjzKSQHcaDoqSLbw"

[provider]
cluster = "Localnet"
wallet = "./deployer.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
