[features]
seeds = false
skip-lint = false
[programs.localnet]
subscription_program = "6beY4Na32mmSym2oibGVBfM43B69CzrY3VQ7Uvu77LaN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/zacharyroberts/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
